### ISSUE TITLE
Unconfident QC Check not behaving as expected

### ISSUE THREAD

**Issue by hellothisisMatt** [phac-nml/bio_hansel#27]
For QC Check 4 (Unconfident Results) bio_hansel is reporting that the downstream subtypes do not exist within the DataFrame. After manually looking at the detailed hansel results, I confirmed that the downstream subtypes' tiles exist within the result. 

Within `subtyper.py`
Lines with:
```
st.non_present_subtypes = [x for x in possible_downstream_subtypes if x not in df['subtype']]
```
should be replaced with something like:
```
st.non_present_subtypes = [x for x in possible_downstream_subtypes if not df['subtype'].str.contains(x).any()]

```
to properly check the DataFrame for the possible downstream subtypes.

**Comment by peterk87** [comment]
Resolved with PR https://github.com/phac-nml/bio_hansel/pull/28
