### ISSUE TITLE
Shorten QC messages - remove repeated terms

### ISSUE THREAD

**Issue by glabbe** [phac-nml/bio_hansel#46]
Suggested enhancement: edit QC messages to remove repeated terms.  
For warnings:  
"WARNING: Low Coverage: Low coverage for all tiles (18.200 < 20 expected)" -> **change to:** "WARNING: Low coverage for all tiles (18.200 < 20 expected)"
For missing tiles:
"FAIL: Missing Tiles Error 1: 11.11% missing tiles; more than 5.00% missing tiles threshold. Low coverage depth (19.1 < 20.0 expected); you may need more WGS data." -> **change to:** "FAIL: 11.11% missing tiles > 5.00% QC setting. Low coverage depth (19.1 < 20.0 expected); you may need more WGS data."
For mixed samples:
"FAIL: Mixed Sample Error 2: Mixed subtype detected. Positive and negative tiles detected for the same target site "2417681" for subtype "1"."  -> **change to:** "FAIL: Mixed subtype detected. Positive and negative tiles detected for the same target site "2417681" for subtype "1"."

**Comment by peterk87** [comment]
Hi @glabbe! Welcome to GitHub :wave: 

Thanks for taking the time to create an issue about this. I've created a pull request to fix this issue in #47 

I'll get @gcttong to review the code before merging into the development branch and creating a new release of `bio_hansel`.

**Comment by glabbe** [comment]
Awesome, thanks Peter!
