### ISSUE TITLE
Change field names to more intuitive ones

### ISSUE THREAD

**Issue by peterk87** [phac-nml/bio_hansel#6]
e.g `n_tiles_matching_positive_total` to  `total_n_positive_tiles_expected`

**Comment by hellothisisMatt** [comment]
Do you want me to do this with all fields containing *total?

**Comment by peterk87** [comment]
Yeah, I think so. We may need more guidance on what should be renamed to what, but I think it's okay to proceed with renaming whatever matches that pattern.

See `Subtype` class:
https://github.com/phac-nml/bio_hansel/blob/master/bio_hansel/subtype.py#L18

and `SUBTYPE_SUMMARY_COLS` global variable:
https://github.com/phac-nml/bio_hansel/blob/master/bio_hansel/subtyper.py#L20

`SUBTYPE_SUMMARY_COLS` is used to order the fields/columns in the DataFrame after `Subtype` instances are exported to dicts and merged into a DataFrame.

If you're using PyCharm, you can probably `Shift+F6` to rename the fields/properties/variables.
